version: '3.8'

services:
  metapus-db:
    image: postgres:latest
    container_name: metapus-db
    restart: always
    environment:
      POSTGRES_USER: metapus
      POSTGRES_PASSWORD: metapus
      POSTGRES_DB: metapus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metapus -d metapus"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: